### ISSUE TITLE
Support for 2023.1

### ISSUE THREAD

**Issue by ebayedq** [dekonoplyov/KeymapNationalizer#10]
This plugin is not supported for 2023.1. Please update the rquirements. Thanks!

**Comment by xyxz-web** [comment]
Would love to see an update too!

**Comment by dekonoplyov** [comment]
Hi folks, try it https://plugins.jetbrains.com/plugin/14625-keymap-nationalizer/versions/stable/315509
also upvote this https://youtrack.jetbrains.com/issue/IDEA-317170/Bundle-KeymapNationalizer-into-Intellij-platform
