### ISSUE TITLE
Duplicate using of Keymap Ctrl+Minus

### ISSUE THREAD

**Issue by Tichu78** [dekonoplyov/KeymapNationalizer#2]
Hi,

with the plugin and a German keyboard there is still a problem with the Keymap for "Collapse" and "Comment with line" comment (Ctrl+Minus):

![image](https://user-images.githubusercontent.com/55097857/97777149-7b110e80-1b6e-11eb-89e8-876ed341f026.png)

Regards,

Sven

**Comment by dekonoplyov** [comment]
Hi Sven! Thank for reaching out.
Collapse should be (Ctrl+ß)?

**Comment by Tichu78** [comment]
Hi Denis,

this is not the case after installing and activating the plugin ...
![image](https://user-images.githubusercontent.com/55097857/97782773-beca3f00-1b93-11eb-8930-03b5d8fd1678.png)
There is no rule to replace - with ß first?

Regards,

Sven

**Comment by dekonoplyov** [comment]
I will add this rule and update plugin.
For now, you can edit rules and add "- with ß".

**Comment by dekonoplyov** [comment]
Fresh version is ready [0.2.4](https://plugins.jetbrains.com/plugin/14625-keymap-nationalizer/versions/stable/101052) :)
