### ISSUE TITLE
Error while trying to generate a layout for french azerty keyboard

### ISSUE THREAD

**Issue by stephanedaviet** [dekonoplyov/KeymapNationalizer#3]
I am trying to generate a french azerty keyboard layout but the dialog prompt me with errors (_Failed to parse key: "%"_). Here is what I have entered in the dialog:
```
a with q
q with a
z with w
w with z
~ with ²
! with 1
@ with 2
# with 3
$ with 4
% with 5
^ with 6
& with 7
* with 8
( with 9
) with 0
_ with °
[ with " 
] with £
; with M
' with %
\ with µ
m with ,
; with .
. with /
/ with §
```

Have you got any idea?

**Comment by dekonoplyov** [comment]
Hi Stéphane, thanks for reaching out!
Sorry for slow reply, I was on holidays :)

I've reproduced this problem and found that there is no KeyCode constant in Java that corresponds to "%".
I'll add a unicode value and update plugin.

**Comment by dekonoplyov** [comment]
Hi Stéphane, % problem is fixed in 0.2.6 version.

**Comment by stephanedaviet** [comment]
Thanks for the fix, but I have updated the plugin and still have some underlined errors on `% with 5` and `' with %` :confused:. For now, I have solved my problem by setting manually a specific shortcut for `Comment with line comments` to `Ctrl + :` (as `/` char is on `:` on Azerty French keyboard).

**Comment by dekonoplyov** [comment]
Sounds weird :( 
Can yon check version "Preferences -> Plugins -> Installed"?

This is how it looks on my computer 
![image](https://user-images.githubusercontent.com/14975482/108072940-90a43880-7078-11eb-8478-b51c65a6d4fc.png)

**Comment by stephanedaviet** [comment]
My bad, it works. The update was failed due to some nitty-gritty proxy problem. Thanks a lot for your time and your fix and sorry again for misdiagnose.
